#!/bin/sh

#monitors are always on
xset s off
xset s noblank
xset -dpms

#Сброс смены раскладки
setxkbmap -option 

pgrep -x sxhkd > /dev/null || sxhkd &

# Multiple monitor support
sh $HOME/.config/bspwm/multy_monitors.sh

#bspc monitor HDMI-0 -d 1 2 3
#bspc monitor DVI-0 -d 4 5 6 



# Window borders (Auto-Generate)
bspc config focus_follows_pointer true
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a org.remmina.Remmina desktop='^3' follow=on
bspc rule -a obsidian desktop='^4' follow=on
bspc rule -a org.mozilla.Thunderbird desktop='^5' follow=on
# start resources
xrdb merge ~/.Xresources

# Random Wallpaper Script
sh $HOME/bin/random_wallpaper

# Run polybar
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# == autostart ==
pkill flameshot; flameshot & alacritty & firefox & remmina & obsidian & thunderbird & keepassxc

# run cursor tracker
#pkill cursor_tracker ; ~/bin/cursor_tracker.sh
